Mysql: {
  Database: "root:test.123@tcp(127.0.0.1:3306)/ydq6_miniprogram?charset=utf8mb4&parseTime=True&loc=Local&readTimeout=500ms"
}

Redis: {
  Addr: "127.0.0.1:13180",
  Password: "test123",
  DbToken: 1
}

Wechat: {
  AppID: "test",
  AppSecret: "test"
}

Ai: {
  ApiKey: "test",
  SecretKey: "test"
}